### ISSUE TITLE
polling during graph interface change results in a crash

### ISSUE THREAD

**Issue by bboettcher3** [libmapper/libmapper#88]
the `mpr_net_init()` function is still processing the new interface request while the graph is polled, resulting in an exception. This has been confirmed by sleeping between polls in webmapper fixing the issue.

```
switching from  {BC5B8435-47B3-4214-87C3-2B3670A81CCF}  to  {BC5B8435-47B3-4214-87C3-2B3670A81CCF}
-- <network>  found interface: {BC5B8435-47B3-4214-87C3-2B3670A81CCF}
Traceback (most recent call last):
  File "C:\Users\brady\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\brady\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\brady\Documents\Github\webmapper\webmapper.py", line 456, in <module>
    server.serve(port=port, poll=poll_and_push, on_open=on_open,
  File "C:\Users\brady\Documents\Github\webmapper\webmapper_http_server.py", line 407, in serve
    poll()
  File "C:\Users\brady\Documents\Github\webmapper\webmapper.py", line 399, in poll_and_push
    g.poll(50)
  File "C:\Users\brady\anaconda3\lib\site-packages\libmapper\mapper.py", line 1133, in poll
    mpr.mpr_graph_poll(self._obj, timeout)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
-- <network>  bus connected to 224.0.1.3:7570
```

**Comment by malloch** [comment]
@bboettcher3 can you check whether the [switch_iface branch](https://github.com/malloch/libmapper/tree/switch_iface) fixes this issue?

**Comment by bboettcher3** [comment]
@malloch this seems to fix it, thanks!

**Comment by malloch** [comment]
@bboettcher3 can you check again with the latest commit? If it still works I will merge and close the issue.

**Comment by bboettcher3** [comment]
Still works, good to merge and close!
