### ISSUE TITLE
missing symbolic link for libmapper.so

### ISSUE THREAD

**Issue by edumeneses** [libmapper/libmapper#94]
I installed libmapper (from [source](https://github.com/libmapper/libmapper), main repository), then downloaded webmapper (from [releases](https://github.com/libmapper/webmapper/releases/tag/2.4.4), v2.4.4), and finally installed mappersession using `pip install mappersession`.

I found the error when trying to run mappersession using `python -m mappersession -h`:

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/libmapper/mapper.py", line 34, in <module>
    mpr = cdll.LoadLibrary(os.path.join(os.path.dirname(__file__), name))
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/libmapper/libmapper.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/edu/.local/lib/python3.10/site-packages/mappersession/__init__.py", line 1, in <module>
    from .mappersession import save, load, unload, load_json, clear, tags
  File "/home/edu/.local/lib/python3.10/site-packages/mappersession/mappersession.py", line 5, in <module>
    import libmapper as mpr
  File "/usr/local/lib/python3.10/dist-packages/libmapper/__init__.py", line 1, in <module>
    from .mapper import *
  File "/usr/local/lib/python3.10/dist-packages/libmapper/mapper.py", line 36, in <module>
    mpr = cdll.LoadLibrary(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmapper.so: cannot open shared object file: No such file or directory
```

The error could be easily solved by adding the symbolic link manually:

```bash
sudo ln -s /usr/local/lib/libmapper.so /usr/local/lib/python3.10/dist-packages/libmapper/libmapper.so
```

I created this issue here, but it might be moved to the libmapper repository as it seems to be a problem with libmapper's [PyPI project](https://pypi.org/project/libmapper/).

**Comment by malloch** [comment]
Thanks for the report @edumeneses. Is libmapper listed when you run `pip list`?

**Comment by edumeneses** [comment]
Yes, It shows as :

```bash
[...]
libmapper                 2.4.4.dev1
[...]
```
